config/routes.rb
Parkalot::Application.routes.draw do
  get 'livemap', to: 'home#livemap', as: 'livemap'
  get 'testmap', to: 'home#testmap', as: 'testmap'
  post 'book_path', to: 'spots#book', as: 'book'


  resources :bookings


  resources :spots


  resources :profiles


  	namespace :mobile do
 		get '', to: 'home#index', as: '/'
 
		authenticated :user do
		    root :to => 'home#index'
		end
		root :to => "home#index"
		devise_for :users
		resources :users  
	end

  authenticated :user do
    	root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :documantation, :image, :latitude, :license, :longitude,:address, :price, :description,:status, :user_id
  belongs_to :user
	mount_uploader :image, SpotUploader
  	geocoded_by :address   # can also be an IP address
	after_validation :geocode
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
    @points = Spot.all.map{|spot| [spot.longitude, spot.latitude] unless spot.longitude.nil? and spot.latitude.nil?}.compact

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spots }
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/new
  # GET /spots/new.json
  def new
    @spot = Spot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
  end

  # POST /spots
  # POST /spots.json
  def create
    @user = current_user
    @spot = @user.spots.new(params[:spot])

    respond_to do |format|
      if @spot.save
        format.html { redirect_to current_user, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  def book
    if user_signed_in?
      @spot = Spot.find(params[:spot][:id])
      #client = BitPay::Client.new 'YOUR_API_KEY'
      #invoice = client.post 'invoice', {:price => 10.00, :currency => 'USD'}
      redirect_to spot_path(@spot)
    else
      redirect_to new_user_registration_path, alert: "You have to register to book a spot!"
    end
  end

  def booked

  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= simple_form_for(@spot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :license %>
    <%= f.input :status %>
    <%= f.input :image %>
    <%= f.input :documantation %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/spots/booked.html.erb
<h2>Congratulations!!</h2>
<h2>You reserved a parking slot </h2>
<p>You have a parking slot in</p>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<div class="container-fluid" style="margin:0px;padding:0px">
  <div class="row" style="margin:0px;padding:0px">
   <div class="col-md-3" style="padding:0px;margin:0px;">
      <link rel="stylesheet" href="http://js.arcgis.com/3.8/js/dojo/dijit/themes/claro/claro.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.8/js/dojo/dojox/widget/ColorPicker/ColorPicker.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.8/js/esri/css/esri.css">

    <style>
      html, body, #map {
        height:100%;
        width:100%;
        margin:0;
        padding:0;
      }
      .dojoxColorPicker {
        position: absolute;
        top: 15px;
        right: 15px;
        -moz-box-shadow: 0 0 7px #888;
        -webkit-box-shadow: 0 0 7px #888;
        box-shadow: 0 0 7px #888;
      }
    </style>

    <script src="http://js.arcgis.com/3.8/"></script>
    <script>
      var map;
      
      require([
        "esri/map", "esri/geometry/Point", 
        "esri/symbols/PictureMarkerSymbol", "esri/graphic",
        "dojo/_base/array", "dojo/dom-style", 
        "dojo/domReady!"
      ], function(
        Map, Point,
        PictureMarkerSymbol, Graphic,
        arrayUtils, domStyle, ColorPicker
      ) {

        map = new Map("map",{
          basemap: "streets",
          center: <%=@points[0]%>,
          zoom: 13,
          minZoom: 2
        });
        
        map.on("load", mapLoaded);
      
        function mapLoaded(){

          var points = <%=@points%>;
          var initColor = "#ce641d";
          var ms = new PictureMarkerSymbol('/assets/marker_info.png',50,60)
          arrayUtils.forEach(points, function(point) {
            var graphic = new Graphic(new Point(point), ms);
            map.graphics.add(graphic);
          });
          
        };
        
        function createSymbol(path, color){
          var markerSymbol = new esri.symbol.SimpleMarkerSymbol();
          markerSymbol.setPath(path);
          markerSymbol.setColor(new dojo.Color(color));
          markerSymbol.setOutline(null);
          return markerSymbol;
        };
      });
    </script>

      <div id="map" style="min-height:550px;height:100%"></div>
    <div id="picker1"></div>
   </div>
   <div class="col-md-9" style="padding-left:20px;">
    <h4 style="color:#2ecc71;margin-top: 40px;padding-left: 0;">Available Listings</h4>
    <table class="table table-hover table-condense">
    
      <% @spots.each do |spot|%>
      <tr>
        <td><a data-toggle="modal" data-target="#myModal<%=spot.id%>" style="cursor:pointer;"><%= image_tag spot.image.url, style: "width:150px;" %></a></td>
        <td><%= spot.address%></td>
        <th style="width:250px;"><%= spot.description%></th>
        <td style="color:#2ecc71;">$<%= spot.price%>/hour</td>
      </tr>
      <% end %>
  
    </table>
   </div>
  </div>
</div>
</div>

<!-- Modal -->
<% @spots.each do |spot|%>

<div class="modal fade" id="myModal<%=spot.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="padding-top:100px;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel" style="color:#2ecc71;padding-left: 20px;">Available Spot</h4>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-6"><%= image_tag spot.image.url, style: "width:260px;" %>
                    <p style="padding-top:15px;font-size:13px"><%= spot.address%>
                        <br> <span style="font-size:15px;color: #2ECC71;">From 14:30h - 21:30. 04/15/2014</span></p>

                </div>
                <div class="col-xs-6">
                    <p>
                        <table>
                            <tr>
                                <td><img src="assets/user.png" alt="David"> </td>
                                <td><%spot.user.email if spot.user%> </td>
                            </tr>    
                        </table>
                        
                    </p><p><span class="glyphicon glyphicon-star"></span> 
      <span class="glyphicon glyphicon-star"></span> 
      <span class="glyphicon glyphicon-star"></span> 
      <span class="glyphicon glyphicon-star-empty"></span> 
     </p>
                    <p style="margin-bottom:0px;"><span class="glyphicon glyphicon-info-sign"></span>
                       <%=spot.description%>. </p>
                    <h6 style="margin:0px;text-decoration:underline;">Contact me</h6>    
                   
                </div>
            </div>
        </div>        
      </div>
      <div class="modal-footer">
        <h4 style="color:#2ECC71;margin:0 0 10px 0;padding:0px;">Your Total: $<%=spot.price%></h4>
        <%= button_to "Book!", book_url(:spot => { :id => spot.id }), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<div class="row" style="margin-top:60px;">
  <div class="col-xs-6 col-sm-4"></div>

  <div class="col-xs-6 col-sm-4" style="text-align:center;"> 

  	<img src="/assets/booked.png" style="width:200px;">
  	<h4 style="color:#2ecc71;padding-left: 20px;">Spot Booked!</h4>

  </div>

  <div class="clearfix visible-xs"></div>
  <div class="col-xs-6 col-sm-4"></div>
</div>