config/routes.rb
Parkalot::Application.routes.draw do
  get 'livemap', to: 'home#livemap', as: 'livemap'
  get 'testmap', to: 'home#testmap', as: 'testmap'
  post 'book_path', to: 'spots#book', as: 'book'


  resources :bookings


  resources :spots


  resources :profiles


  	namespace :mobile do
 		get '', to: 'home#index', as: '/'
 
		authenticated :user do
		    root :to => 'home#index'
		end
		root :to => "home#index"
		devise_for :users
		resources :users  
	end

  authenticated :user do
    	root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :credit_account, :fullname, :name, :picture, :surname, :telephone, :user_id
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :name %>
    <%= f.input :surname %>
    <%= f.input :fullname %>
    <%= f.input :telephone %>
    <%= f.input :picture %>
    <%= f.input :credit_account %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Fullname</th>
    <th>Telephone</th>
    <th>Picture</th>
    <th>Credit account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.user_id %></td>
    <td><%= profile.name %></td>
    <td><%= profile.surname %></td>
    <td><%= profile.fullname %></td>
    <td><%= profile.telephone %></td>
    <td><%= profile.picture %></td>
    <td><%= profile.credit_account %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @profile.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @profile.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @profile.surname %>
</p>

<p>
  <b>Fullname:</b>
  <%= @profile.fullname %>
</p>

<p>
  <b>Telephone:</b>
  <%= @profile.telephone %>
</p>

<p>
  <b>Picture:</b>
  <%= @profile.picture %>
</p>

<p>
  <b>Credit account:</b>
  <%= @profile.credit_account %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>