config/routes.rb
Parkalot::Application.routes.draw do
  get 'livemap', to: 'home#livemap', as: 'livemap'
  get 'testmap', to: 'home#testmap', as: 'testmap'
  post 'book_path', to: 'spots#book', as: 'book'


  resources :bookings


  resources :spots


  resources :profiles


  	namespace :mobile do
 		get '', to: 'home#index', as: '/'
 
		authenticated :user do
		    root :to => 'home#index'
		end
		root :to => "home#index"
		devise_for :users
		resources :users  
	end

  authenticated :user do
    	root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :booker_id, :check_in, :check_out, :renter_id, :spot_id
  belongs_to :renter, :class_name => 'User', :foreign_key => :renter_id
  belongs_to :booker, :class_name => 'User', :foreign_key => :booker_id
  belongs_to :spot

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :renter_id %>
    <%= f.input :booker_id %>
    <%= f.input :spot_id %>
    <%= f.input :check_in %>
    <%= f.input :check_out %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Renter</th>
    <th>Booker</th>
    <th>Spot</th>
    <th>Check in</th>
    <th>Check out</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.renter_id %></td>
    <td><%= booking.booker_id %></td>
    <td><%= booking.spot_id %></td>
    <td><%= booking.check_in %></td>
    <td><%= booking.check_out %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Renter:</b>
  <%= @booking.renter_id %>
</p>

<p>
  <b>Booker:</b>
  <%= @booking.booker_id %>
</p>

<p>
  <b>Spot:</b>
  <%= @booking.spot_id %>
</p>

<p>
  <b>Check in:</b>
  <%= @booking.check_in %>
</p>

<p>
  <b>Check out:</b>
  <%= @booking.check_out %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>