config/routes.rb
Parkalot::Application.routes.draw do
  get 'livemap', to: 'home#livemap', as: 'livemap'
  get 'testmap', to: 'home#testmap', as: 'testmap'
  post 'book_path', to: 'spots#book', as: 'book'


  resources :bookings


  resources :spots


  resources :profiles


  	namespace :mobile do
 		get '', to: 'home#index', as: '/'
 
		authenticated :user do
		    root :to => 'home#index'
		end
		root :to => "home#index"
		devise_for :users
		resources :users  
	end

  authenticated :user do
    	root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">

  <!-- logo -->
  <a href="<%= root_path %>" >
    <img src="/assets/logo.png" alt="" style="margin-top:22px;width:200px;">
  </a>
  <!-- end of logo -->

  <nav>
    
    <ul>
      <li><a href="#about">About</a></li>
      <li><a href="<%=livemap_path%>">Live Map</a></li>
      <!-- <li><a href="#clients">Mobile App</a></li>
     <li><a href="#team">Team</a></li>
      <li><a href="#contact">Contact</a></li>-->
      <%if user_signed_in?%>
       <li> <a href="<%= user_path(current_user) %>" class="btn" style="height: 45px;">List your spot</a></li>
       <li>
       <ul>
          <%= render 'layouts/navigation_links' %>
        </ul>
       </li> 
      <%else%>
        <li> <a href="<%= new_user_registration_path %>" class="btn" style="height: 45px;">List your spot</a></li>
      <%end%>

  </ul>
  </nav><!-- end of navigation -->

</div><!-- end of container in header -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="description" content="">
 <meta name="viewport" content="width=device-width, user-scalable=no">
 <title><%= content_for?(:title) ? yield(:title) : "Parkalot" %></title>
 <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Parkalot" %>">
 <%= stylesheet_link_tag "main/application", media: "all" %>
 <%= javascript_include_tag "main/application" %>
 <link href='http://fonts.googleapis.com/css?family=Roboto:300,700' rel='stylesheet' type='text/css'>
 <%= csrf_meta_tags %>
</head>
<body id='top'>
  <div class="layout">

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="content">

     <%= render 'layouts/messages' %>
     <%= yield %>
   </div> <!-- end of content -->

   <!-- Begin of  .to_the_top --> 
   <div id="to_the_top"></div>
   <!-- End of .to_the_top  -->

 </div><!-- end of layout -->
 <!-- Footer Section -->
 <footer>
  <div class="container">
    <div class="left">
      <a href="http://www.esri.com/"><img src="/assets/esrilogo.png"  style="width:100px;padding-top:15px;" alt=""></a>
      <a href="https://www.heroku.com/"><img src="/assets/herokulogo.png"  style="width:100px;padding-top:20px;" alt=""></a>
      <small><a href="">Thanks for their support.</i></small></a>

      <small> Derechos de autor Iago Rodríguez

Autorizado en virtud de la Licencia de Apache, Versión 2.0 (la "Licencia"); se prohíbe utilizar este archivo excepto en cumplimiento de la Licencia.

Podrá obtener una copia de la Licencia en:

http://www.apache.org/licenses/LICENSE-2.0</small>
  </footer> <!-- end of footer -->

</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <!--Declare page as mobile friendly --> 
      <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
      <!-- Declare page as iDevice WebApp friendly -->
      <meta name="apple-mobile-web-app-capable" content="yes"/>
      <!-- iDevice WebApp Splash Screen, Regular Icon, iPhone, iPad, iPod Retina Icons -->
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/splash/splash-icon.png"> 
      <!-- iPhone 3, 3Gs -->
      <link rel="apple-touch-startup-image" href="images/splash/splash-screen.png"      media="screen and (max-device-width: 320px)" /> 
      <!-- iPhone 4 -->
      <link rel="apple-touch-startup-image" href="images/splash/splash-screen@2x.png"     media="(max-device-width: 480px) and (-webkit-min-device-pixel-ratio: 2)" /> 
      <!-- iPhone 5 -->
      <link rel="apple-touch-startup-image" sizes="640x1096" href="images/splash/splash-screen@3x.png" />

    <title><%= content_for?(:title) ? yield(:title) : "Parkalot" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Parkalot" %>">
    <%= stylesheet_link_tag "mobile/application", media: "all" %>
    <%= javascript_include_tag "mobile/application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>

    <div id="sidebar" class="page-sidebar">
        <div class="page-sidebar-scroll">
            <div class="nav-item">
                <a href="#" class="nav-icon nav-coach coach-icon">PAGE COACH</a>
            </div>
            <div class="nav-item">
                <a href="index.html" class="nav-icon home-icon">HOMEPAGE</a>
            </div>
            <div class="nav-item">
                <a href="type.html" class="nav-icon type-icon">TYPOGRAPHY</a>
            </div>
            <div class="nav-item">
                <a href="jquery.html" class="nav-icon jquery-icon">jQUERY</a>
            </div>
            <div class="nav-item">
                <a href="other.html" class="nav-icon other-icon">OTHERS</a>
            </div>
            <div class="nav-item">
                <a href="folio.html" class="nav-icon folio-icon">PORTFOLIO</a>
            </div>
            <div class="nav-item">
                <a href="gallery.html" class="nav-icon gallery-icon">GALLERY</a>
            </div>
            <div class="nav-item">
                <a href="video.html" class="nav-icon videos-icon">VIDEOS</a>
            </div>
          </div>
    </header>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>